# Test against the latest version of this Node.js version
environment:
  nodejs_version: "7"

version: 1.0.{build}
image: Visual Studio 2017

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # Output useful info for debugging.
  - npm --version
  - node --version

  # install modules
  - npm install -g gulp 
  - npm install
  - gulp init --threshold=1

# Post-install test scripts.
test_script:
  # run tests
  - gulp test

# Don't actually build.
build_script: 
  - gulp build

